---
title: "load_crop_data"
format: html
---

```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(tmap)
library(sf)
library(here)
library(stars)
library(spData)
library(terra)
```

```{r}


#rivers <- read_sf(here::here('data', 'HydroRIVERS_v10_shp', 'HydroRIVERS_v10_shp', 'HydroRIVERS_v10.shp')) %>% 
  #clean_names()

current_dams <- read_sf(here::here('data', 'GRanD_Version_1_3')) %>% 
  clean_names()

future_dams <- read_csv(here::here('data', 'FHReD_2015_future_dams', 'FHRed_2015_future_dams_CSV.csv')) %>% 
  clean_names()

global_pop_sf <- read_stars(here::here('data', 'global_pop_2020_CN_1km_R2025A_UA_v1.tif')) %>% 
  clean_names()

global_pop_rast <- rast(here::here('data', 'global_pop_2020_CN_1km_R2025A_UA_v1.tif')) %>% 
  clean_names()

mekong_basin <- read_sf(here::here('data', 'Major_basins', 'Major_basins.shp')) %>% 
  clean_names()

basin_level3 <- read_sf(here::here('data', 'asia_basin_levels', 'hybas_as_lev03_v1c.shp')) %>% 
  clean_names()

basin_level4 <- read_sf(here::here('data', 'asia_basin_levels', 'hybas_as_lev04_v1c.shp')) %>% 
  clean_names()

asia_rivers <- read_sf(here::here('data', 'asia_HydroRIVERS.gdb', 'HydroRIVERS_v10_as.gdb')) %>% 
  clean_names()

#world <- spData::world
#USA <- world %>% filter(name_long == 'United States')
#Africa <- world %>% filter(continent == 'Africa')

```

```{r}
future_dams <- st_as_sf(future_dams,
         coords = c('lon_cleaned', 'lat_cleaned'), 
         crs = st_crs(current_dams))
```

```{r}
asia_rivers %>% 
  group_by(ord_clas) %>% 
  summarise(n = n())

asia_rivers %>% 
  filter(ord_clas == 3) %>% 
  tm_shape() + 
  tm_lines()


asia_rivers %>% 
  filter(ord_clas == 4) %>% 
  tm_shape() + 
  tm_lines()

asia_rivers %>% 
  filter(ord_clas == 2) %>% 
  tm_shape() + 
  tm_lines()

asia_rivers3 <- asia_rivers %>% 
  filter(ord_clas == 3)

asia_rivers2 <- asia_rivers %>% 
  filter(ord_clas == 2)
```


```{r}
current_dams <- st_make_valid(current_dams)
future_dams <- st_make_valid(future_dams)
nepal_basin <- st_make_valid(nepal_basin)
asia_rivers2 <- st_make_valid(asia_rivers2)

```

Limit to mekon basin 
```{r}

current_dams_mekong <- st_intersection(mekong_basin, current_dams)
future_dams_mekong <- st_intersection(mekong_basin, future_dams)
#river_africa <- st_intersection(Africa, rivers)

river_africa <- st_filter(rivers, mekong_basin)

pop_mekong <- crop(global_pop, mekong_basin)
pop_mekong <- mask(pop_mekong, mekong_basin)

current_dams_mekong <- 
  
```

```{r}
class(mekong_basin)

```

```{r}
# Selecting Napels water basin at level 3 
basin_level3 %>% 
  filter(hybas_id == 4030025450) %>% 
  tm_shape(basin_level3) + 
  tm_polygons(col = 'hybas_id') + 
  tm_basemap('OpenStreetMap')

nepal_basin <- basin_level3 %>% 
  filter(hybas_id == 4030025450)

tm_shape(nepal_basin) + 
  tm_polygons(fill_alpha = 0.2, lwd = 2) + 
  tm_basemap('OpenStreetMap')
```


```{r}
tm_shape(current_dams) + 
  tm_dots(fill = 'blue') + 
  tm_shape(future_dams) + 
  tm_dots(fill = 'darkred') +
  tm_basemap('Esri.OceanBasemap')
```

```{r}
asia_river_3 <- asia_rivers %>% 
  filter(ord_flow >= 3)

tm_shape(basin_level3) + 
  tm_polygons() + 
  tm_shape(current_dams) + 
  tm_dots(fill = 'blue') + 
  tm_shape(future_dams) + 
  tm_dots(fill = 'darkred') 


tm_shape(asia_river_3) + 
  tm_lines()

```

Crop to the nepal basin 
```{r}
nepal_current_dams <- st_intersection(nepal_basin, current_dams)
nepal_future_dams <- st_intersection(nepal_basin, future_dams)
#nepal_rivers3 <- st_intersection(nepal_basin, asia_rivers3)
#nepal_rivers2 <- st_intersection(nepal_basin, asia_rivers2)

```

```{r}
tm_shape(nepal_basin) + 
  tm_polygons(fill_alpha = 0.5, lwd = 2.5) + 
  tm_basemap('Esri.WorldTopoMap') + 
  tm_shape(nepal_current_dams) + 
  tm_dots(fill = "red") + 
  tm_shape(nepal_future_dams) + 
  tm_dots(fill = "blue") + 
  tm_add_legend(type = "polygons", 
                labels = c("Current Dams", "Future Dams"), 
                fill = c("red", "blue"), 
                title = "Dam Status") + 
  tm_title(text = "Dams in Nepal") + 
  tm_compass() + 
  tm_scalebar()


```

